---
- name: Create configuration directory
  file:
    path: "{{ gordon_config_dir }}"
    state: directory
    owner: "{{ gordon_user }}"
    group: "{{ gordon_group }}"
    mode: '0755'

- name: Generate configuration file
  template:
    src: config.yaml.j2
    dest: "{{ gordon_config_dir }}/config.yaml"
    owner: "{{ gordon_user }}"
    group: "{{ gordon_group }}"
    mode: '0644'
  notify: Restart gordon-watcher

- name: Configure logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/gordon-watcher
    owner: root
    group: root
    mode: '0644'
  when: gordon_watcher_logrotate_enabled
