global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gordon-watcher'
    static_configs:
      - targets: ['gordon-watcher:9100']
        labels:
          service: 'watcher'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
